version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 219315770087.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t allomedia-backend ./backend/Dockerfile .
      - docker tag allomedia-backend:latest 219315770087.dkr.ecr.us-east-1.amazonaws.com/allomedia-backend:latest
      
      - docker build -t allomedia-frontend ./frontend/Dockerfile .
      - docker tag allomedia-frontend:latest 219315770087.dkr.ecr.us-east-1.amazonaws.com/allomedia-frontend:latest
  post_build:
    commands:
      - docker push 219315770087.dkr.ecr.us-east-1.amazonaws.com/allomedia-backend:latest
      - docker push 219315770087.dkr.ecr.us-east-1.amazonaws.com/allomedia-frontend:latest