services:


  backend:
  allomedia-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: development
    image: allomedia-backend
    command: npm run dev
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
  frontend: 
      - 4000:4000
    depends_on:
      - mongo
  frontend: 
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: development
    image: allomedia-frontend
    command: npm run dev
    env_file:
      - ./frontend/.env
    ports:
      - 5173:5173
    depends_on:
      - mongo
  mongo:
    image: mongo
    
  
