services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: development
    image: backend
    command: npm run dev
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
  frontend: 
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: development
    image: frontend
    command: npm run dev
    env_file:
      - ./frontend/.env
    ports:
      - 5173:5173
  mongo:
    image: mongo
    
  
