name: AlloMedia CI/CD

on:
  push:
    branches:
      - rachid

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: run tests
        run: cd backend && npm test

      # - name: run decker compose
      #   run: docker compose up

      - name: Login to AWS ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 219315770087.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and tag Docker images
        run: |
          docker-compose build allomedia-frontend
          docker tag allomedia-frontend:latest 219315770087.dkr.ecr.us-east-1.amazonaws.com/allomedia-frontend:latest

          docker-compose build allomedia-backend
          docker tag allomedia-backend:latest 219315770087.dkr.ecr.us-east-1.amazonaws.com/allomedia-backend:latest

      - name: Push Docker images to AWS ECR
        run: |
          docker push 219315770087.dkr.ecr.us-east-1.amazonaws.com/allomedia-backend:latest
          docker push 219315770087.dkr.ecr.us-east-1.amazonaws.com/allomedia-frontend:latest
