name: AlloMedia CI

on:
  push:
    branches:
      - rachid

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: run tests
        run: npm test


